### ISSUE TITLE
Facebook Login Failed

### ISSUE THREAD

**Issue by chandrashekharkhod** [leen3o/mvcforum#25] opened 2015-07-18 14:49 UTC
MVCForum v6.0
Login with Facebook failed on redirect:

Debug the error location: 
File: FacebookOAuthController.cs
Everything goes fine but break down on below line: 

if (string.IsNullOrEmpty(resultMessage.Message))
                     {
                         // Initialize the Facebook service (no calls are made here)
                         var service = FacebookService.CreateFromAccessToken(userAccessToken);

                        var user = service.Users.GetUser(); // HERE user = null //

Throws error: Object reference not set to of an object.

**Comment by leen3o** [comment] 2015-07-19 07:02
This is either a permissions problem with your Facebook app, or a problem with SkyBrud.Social. 

https://github.com/abjerner/Skybrud.Social

As we use that library to do the Facebook login.

**Comment by abjerner** [comment] 2015-08-12 19:44
I have made a new release of Skybrud.Social - `v0.9.4` - that fixes the parsing error (which was caused by a gender not being present in JSON).

**Comment by leen3o** [comment] 2015-08-15 06:10
This is fixed in v1.7

**Closed by leen3o** 2015-08-15 06:10 UTC
